In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import statistics as st

In [18]:
# Data download from sklearn
from sklearn.datasets import load_iris
data=load_iris().data
target=load_iris().target
df_data=pd.DataFrame(data,columns=['sepal_length','sepal_width','petal_length','petal_width'])
df_target=pd.DataFrame(target,columns=['target'])

In [19]:
df_merged=pd.merge(df_data, df_target, left_index=True, right_index=True)

In [20]:
df_merged

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [21]:
df_merged.head()

   sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [22]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   target        150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [23]:
df_merged.describe()

       sepal_length  sepal_width  petal_length  petal_width      target
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.057333      3.758000     1.199333    1.000000
std        0.828066     0.435866      1.765298     0.762238    0.819232
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.350000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

Nous constatons qu'il n'y a pas de données manquantes, nous pouvons donc procéder à l'analyse.

In [24]:
X=df_merged[['sepal_length','sepal_width','petal_length','petal_width']]
y=df_merged['target']

print(X.shape)
print(y.shape)

(150, 4)
(150,)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)

In [26]:
%%time
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(5)
knn_clf.fit(X_train, y_train)

CPU times: total: 15.6 ms
Wall time: 36.6 ms

KNeighborsClassifier()

In [27]:
y_pred = knn_clf.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9333333333333333

In [29]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
cm = confusion_matrix(y_test, y_pred)
disp=ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()

In [30]:
!git status

On branch branche3
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	analyse2.ipynb

nothing added to commit but untracked files present (use "git add" to track)

In [31]:
!git version

git version 2.52.0.windows.1

In [32]:
y_pred

array([1, 1, 1, 2, 2, 0, 0, 1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 0, 2, 1, 0, 0,
       2, 0, 1, 0, 0, 2, 1, 2])

Evaluate impact of accuracy

In [34]:
k=[10,20,30,40,50]

average=[]
correct_predictions=[]

for i in k:
    score=[]
    correct=[]
    for j in range(10):
        
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
        knn_clf = KNeighborsClassifier(i)
        knn_clf.fit(X_train, y_train)
        y_pred = knn_clf.predict(X_test)
        score.append(round(accuracy_score(y_test, y_pred),2))    #we'll store the accuracy score of each run in the score list
        
        #accuracy score = number of correct predictions / total number of predictions
        #so number of correct predictions=accuracy score*total number of predictions
        # from data splitting info, we know that total number of predictions is 30
            
        corr=accuracy_score(y_test, y_pred)*30  #here we're calculating the number of correct predictions
        correct.append(round(corr))   #number of correct predictions will be stored in the correct list
        
    average.append(round(st.mean(score),2)) #this list contains the average accuracy score for each k
    correct_predictions.append(round(st.mean(correct))) #this list contains the average number of correct predictions for each k
    
#let's create a dataframe to store all values

kimpact_df=pd.DataFrame(data=[1,3,5,7,10,20,30,40,50], columns=['k_values'])
kimpact_df['average_score']=average
kimpact_df['correct_predictions']=correct_predictions
kimpact_df

ValueError: Length of values (5) does not match length of index (9)